db:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://${POSTGRES_HOST:-localhost}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}

server:
  applicationConnectors:
    - type: http
      port: ${MARQUEZ_PORT:-5000}
  adminConnectors:
    - type: http
      port: ${MARQUEZ_ADMIN_PORT:-5001}

logging:
  level: INFO
  appenders:
    - type: console
